### ISSUE TITLE
Incluir JFA em domínio público

### ISSUE THREAD

**Issue by ghost** [blivre/BibliaLivre#5]
Adotando um único formato de arquivo (JSON? #4 ) seria interessante incluir no repo traduções de [1849, 1850, etc.](http://www.almeidarecebida.org/).

Com isso seria bem prático fazer um diff entre o original (v1850?) e os ramos (um deles seria o biblialivre). Além de ser mais prático para análise das diferenças seria mais fácil contribuir ao projeto.

**Comment by blivre** [comment]
Eu não sei se a transcrição das Almeidas de 1848 e 1850 em http://www.almeidarecebida.org/?p=1 estão boas. 
A Almeida de 1911 está em boa qualidade.

**Comment by ghost** [comment]
Perfeito @blivre, não vejo problemas em usar a de 1911.

**Comment by ghost** [comment]
Por favor @blivre, teria como você me fornecer o link para a versão 1911 que você tem à disposição?

**Comment by blivre** [comment]
Olá, Guilherme. O link disponível é:
https://sites.google.com/site/manuscript4u/download

2016-07-09 20:20 GMT-03:00 Guilherme V. Campos notifications@github.com:

> Por favor @blivre https://github.com/blivre, teria como você me
> fornecer o link para a versão 1911 que você tem a disposição?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/blivre/BibliaLivre/issues/5#issuecomment-231561185,
> or mute the thread
> https://github.com/notifications/unsubscribe/AJ0Mk3bd8y7VB_8G1urtlk-f_73gxQAnks5qUCy9gaJpZM4I98ke
> .

## 

---

Diego Renato dos Santos
